[tool.poetry]
name = "secas-ssa"
version = "0.2.0"
description = ""
authors = ["Brendan Ward <bcward@astutespruce.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10,<3.13"
geopandas = "^0.14.4"
affine = "^2.4.0"
aiofiles = "^23.2.1"
fastapi = "^0.111.0"
numpy = "^1.26.4"
pandas = "^2.2.2"
python-dotenv = "^1.0.1"
python-multipart = "^0.0.9"
rasterio = "^1.3.10"
sentry-sdk = "^1.38.0"
uvicorn = "^0.27.1"
pyarrow = "^16.1.0"
arq = "^0.26.0"
openpyxl = "^3.1.3"
shapely = "^2.0.4"
pyogrio = "^0.8.0"
hiredis = "^2.2.2"

[tool.poetry.group.dev.dependencies]
httpx = {extras = ["http2"], version = "^0.27.0"}
watchfiles = "^0.22.0"
ruff = "^0.4.7"
watchgod = "^0.8.2"
progress = "^1.6"
cython = "^3.0.10"

[tool.ruff]
exclude = ['.scratch']