[tool.poetry]
name = "secas-ssa"
version = "0.1.0"
description = ""
authors = ["Brendan Ward <bcward@astutespruce.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pyogrio = "^0.4.1"
geopandas = "^0.11.1"
affine = "^2.3.1"
aiofiles = "^0.8.0"
fastapi = "^0.79.0"
Jinja2 = "^3.1.2"
numpy = "^1.23.1"
pandas = "^1.4.3"
Pillow = "^9.2.0"
python-dotenv = "^0.20.0"
python-multipart = "^0.0.5"
rasterio = "^1.3.0"
sentry-sdk = "^1.9.0"
uvicorn = "^0.18.2"
weasyprint = "^56.1"
pygeos = "^0.12.0"
pyarrow = "^8.0.0"
arq = { version = "0.23a1", allow-prereleases = true }
openpyxl = "^3.0.10"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
Cython = "^0.29.30"
flake8 = "^4.0.1"
pylint = "^2.14.5"
watchgod = "^0.8.2"
progress = "^1.6"
httpx = { extras = ["http2"], version = "^0.23.0" }


[build-system]
# numpy and Cython are required to execute setup.py to build Cython extensions
requires = ["poetry-core>=1.0.0", "setuptools", "wheel", "numpy", "Cython"]
build-backend = "poetry.core.masonry.api"
