[tool.poetry]
name = "secas-ssa"
version = "0.1.0"
description = ""
authors = ["Brendan Ward <bcward@astutespruce.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
geopandas = "^0.12.2"
affine = "^2.4.0"
aiofiles = "^23.1.0"
fastapi = "^0.95.0"
numpy = "^1.24.2"
pandas = "^1.5.3"
Pillow = "^9.4.0"
python-dotenv = "^1.0.0"
python-multipart = "^0.0.6"
rasterio = "^1.3.6"
sentry-sdk = "^1.18.0"
uvicorn = "^0.21.1"
pyarrow = "^11.0.0"
arq = "^0.25.0"
openpyxl = "^3.1.2"
shapely = "^2.0.1"
pyogrio = "^0.5.1"
hiredis = "^2.2.2"

[tool.poetry.dev-dependencies]
black = "^23.3.0"
Cython = "^0.29.30"
watchgod = "^0.8.2"
progress = "^1.6"
httpx = {extras = ["http2"], version = "^0.23.3"}
watchfiles = "^0.19.0"
ruff = "^0.0.260"


[build-system]
# numpy and Cython are required to execute setup.py to build Cython extensions
requires = ["poetry-core>=1.0.0", "setuptools", "wheel", "numpy", "Cython"]
build-backend = "poetry.core.masonry.api"
