[tool.poetry]
name = "secas-ssa"
version = "0.2.0"
description = ""
authors = ["Brendan Ward <bcward@astutespruce.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10,<3.13"
geopandas = "^0.14.3"
affine = "^2.4.0"
aiofiles = "^23.2.1"
fastapi = "^0.110.0"
numpy = "^1.26.4"
pandas = "^2.2.1"
python-dotenv = "^1.0.1"
python-multipart = "^0.0.9"
rasterio = "^1.3.9"
sentry-sdk = "^1.38.0"
uvicorn = "^0.27.1"
pyarrow = "^15.0.0"
arq = "^0.25.0"
openpyxl = "^3.1.2"
shapely = "^2.0.3"
pyogrio = "^0.7.2"
hiredis = "^2.2.2"

[tool.poetry.group.dev.dependencies]
httpx = {extras = ["http2"], version = "^0.27.0"}
watchfiles = "^0.21.0"
cython = "^3.0.8"
ruff = "^0.3.0"
watchgod = "^0.8.2"
progress = "^1.6"

